services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - backend_parquet:/app/parquet
      - backend_db:/app/db
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_UPLOAD_SIZE=10485760  # 10MB in bytes
      - UPLOAD_DIR=/app/uploads
      - PARQUET_DIR=/app/parquet
      - DB_PATH=/app/metadata.db
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  backend_uploads:
    driver: local
  backend_parquet:
    driver: local
  backend_db:
    driver: local
